# This file was generated by Codebase-Generator, do not edit directly
"""
Responses component for Recipe Executor integrating OpenAI Responses API.
Provides factory function for creating configured OpenAIResponsesModel instances.
"""

from pydantic_ai.models.openai import OpenAIResponsesModel

__all__ = ["create_openai_responses_model"]


def create_openai_responses_model(model_name: str) -> OpenAIResponsesModel:
    """
    Instantiate and return an OpenAIResponsesModel for the given model name.

    Args:
        model_name: The identifier of the OpenAI model (e.g., "gpt-4o").

    Returns:
        An OpenAIResponsesModel instance configured to use the Responses API.

    Raises:
        ValueError: If model_name is invalid or model initialization fails.
    """
    if not isinstance(model_name, str) or not model_name.strip():
        raise ValueError("model_name must be a non-empty string")

    try:
        model = OpenAIResponsesModel(model_name)
    except Exception as e:
        # Provide clear context in error message
        raise ValueError(f"Failed to initialize OpenAIResponsesModel for '{model_name}': {e}") from e

    return model
