# This file was generated by Codebase-Generator, do not edit directly
"""
Utility functions for generating Pydantic models from JSON-Schema object definitions.
"""

from typing import Any, Dict, List, Optional, Type, Tuple

from pydantic import BaseModel, create_model

__all__ = ["json_object_to_pydantic_model"]


def json_object_to_pydantic_model(schema: Dict[str, Any], model_name: str = "SchemaModel") -> Type[BaseModel]:
    """
    Convert a JSON-Schema object fragment into a Pydantic BaseModel subclass.

    Args:
        schema: A JSON-Schema fragment describing an object (must be type "object").
        model_name: Name for the generated Pydantic model class.

    Returns:
        A subclass of BaseModel corresponding to the schema.

    Raises:
        ValueError: If the schema is invalid or unsupported.
    """
    # Validate root schema
    if not isinstance(schema, dict):
        raise ValueError("Schema must be a dictionary.")
    if "type" not in schema:
        raise ValueError('Schema missing required "type" property.')
    if schema["type"] != "object":
        raise ValueError('Root schema type must be "object".')

    properties = schema.get("properties", {})
    if not isinstance(properties, dict):
        raise ValueError('Schema "properties" must be a dictionary if present.')
    required = schema.get("required", [])
    if not isinstance(required, list):
        raise ValueError('Schema "required" must be a list if present.')

    class _Counter:
        """Simple counter for deterministic nested model names."""

        def __init__(self) -> None:
            self._count = 0

        def next(self) -> int:
            self._count += 1
            return self._count

    counter = _Counter()

    def _parse_field(field_schema: Dict[str, Any], field_name: str, parent_name: str) -> Tuple[Any, Any]:
        if not isinstance(field_schema, dict):
            raise ValueError(f"Schema for field '{field_name}' must be a dictionary.")
        if "type" not in field_schema:
            raise ValueError(f"Schema for field '{field_name}' missing required 'type'.")

        ftype = field_schema["type"]
        if ftype == "string":
            return str, ...
        if ftype == "integer":
            return int, ...
        if ftype == "number":
            return float, ...
        if ftype == "boolean":
            return bool, ...
        if ftype == "object":
            nested_name = f"{parent_name}_{field_name.capitalize()}Obj{counter.next()}"
            nested_model = _build_model(field_schema, nested_name)
            return nested_model, ...
        if ftype in ("array", "list"):
            items = field_schema.get("items")
            if not isinstance(items, dict):
                raise ValueError(f"Array field '{field_name}' missing valid 'items' schema.")
            item_type, _ = _parse_field(items, f"{field_name}_item", parent_name)
            return List[item_type], ...
        # Fallback for unsupported types
        return Any, ...

    def _wrap_optional(
        field_schema: Dict[str, Any], is_required: bool, field_name: str, parent_name: str
    ) -> Tuple[Any, Any]:
        type_hint, default = _parse_field(field_schema, field_name, parent_name)
        if not is_required:
            type_hint = Optional[type_hint]  # type: ignore
            default = None
        return type_hint, default

    def _build_model(obj_schema: Dict[str, Any], name: str) -> Type[BaseModel]:
        if not isinstance(obj_schema, dict):
            raise ValueError(f"Nested schema '{name}' must be a dictionary.")
        if obj_schema.get("type") != "object":
            raise ValueError(f"Nested schema '{name}' type must be 'object'.")

        props = obj_schema.get("properties", {})
        if not isinstance(props, dict):
            raise ValueError(f"Nested schema '{name}' properties must be a dictionary.")
        req = obj_schema.get("required", [])
        if not isinstance(req, list):
            raise ValueError(f"Nested schema '{name}' required must be a list.")

        fields: Dict[str, Tuple[Any, Any]] = {}
        for prop_name, prop_schema in props.items():
            is_req = prop_name in req
            hint, default = _wrap_optional(prop_schema, is_req, prop_name, name)
            fields[prop_name] = (hint, default)

        return create_model(name, **fields)  # type: ignore

    return _build_model(schema, model_name)
