# This file was generated by Codebase-Generator, do not edit directly
import os
import ast
from typing import Any, Dict
import logging

from recipe_executor.steps.base import BaseStep, StepConfig
from recipe_executor.protocols import ContextProtocol
from recipe_executor.utils.templates import render_template

__all__ = ["ExecuteRecipeConfig", "ExecuteRecipeStep"]


def _render_override(value: Any, context: ContextProtocol) -> Any:
    """
    Recursively render and parse override values.

    - Strings are template-rendered, then if the result is a valid Python literal (dict or list), parsed via ast.literal_eval.
    - Lists and dicts are processed recursively.
    - Other types are returned as-is.
    """
    if isinstance(value, str):
        rendered = render_template(value, context)
        try:
            parsed = ast.literal_eval(rendered)
        except (ValueError, SyntaxError):
            return rendered
        if isinstance(parsed, (dict, list)):
            return parsed
        return rendered
    if isinstance(value, list):  # type: ignore[type-arg]
        return [_render_override(item, context) for item in value]
    if isinstance(value, dict):  # type: ignore[type-arg]
        return {key: _render_override(val, context) for key, val in value.items()}
    return value


class ExecuteRecipeConfig(StepConfig):
    """Config for ExecuteRecipeStep.

    Fields:
        recipe_path: Path to the sub-recipe to execute (templateable).
        context_overrides: Optional values to override in the context.
    """

    recipe_path: str
    context_overrides: Dict[str, Any] = {}


class ExecuteRecipeStep(BaseStep[ExecuteRecipeConfig]):
    """Step to execute a sub-recipe with shared context and optional overrides."""

    def __init__(
        self,
        logger: logging.Logger,
        config: Dict[str, Any],
    ) -> None:
        validated: ExecuteRecipeConfig = ExecuteRecipeConfig.model_validate(config)
        super().__init__(logger, validated)

    async def execute(self, context: ContextProtocol) -> None:
        """
        Execute a sub-recipe located at the rendered recipe_path.

        Applies context_overrides before execution, shares the same context,
        and logs progress.
        """
        # Resolve and validate the sub-recipe path
        path = render_template(self.config.recipe_path, context)
        if not os.path.isfile(path):
            raise FileNotFoundError(f"Sub-recipe file not found: {path}")

        # Apply context overrides with templating and literal eval parsing
        for key, override_value in self.config.context_overrides.items():
            rendered_value = _render_override(override_value, context)
            context[key] = rendered_value

        try:
            # Import here to avoid circular dependencies
            from recipe_executor.executor import Executor

            self.logger.info(f"Starting sub-recipe execution: {path}")
            executor = Executor(self.logger)
            await executor.execute(path, context)
            self.logger.info(f"Completed sub-recipe execution: {path}")
        except Exception as exc:
            self.logger.error(f"Error executing sub-recipe '{path}': {exc}")
            raise RuntimeError(f"Failed to execute sub-recipe '{path}': {exc}") from exc
