# This file was generated by Codebase-Generator, do not edit directly
import json
import os
import logging
from typing import Any, Dict, List, Union

import yaml

from recipe_executor.protocols import ContextProtocol
from recipe_executor.steps.base import BaseStep, StepConfig
from recipe_executor.utils.templates import render_template


class ReadFilesConfig(StepConfig):
    """
    Configuration for ReadFilesStep.

    Fields:
        path (Union[str, List[str]]): Path, comma-separated string, or list of paths to read (may be templated).
        content_key (str): Key under which to store content in context (may be templated).
        optional (bool): If True, missing files are ignored (default: False).
        merge_mode (str): How to merge multiple files: "concat" or "dict" (default: "concat").
    """

    path: Union[str, List[str]]
    content_key: str
    optional: bool = False
    merge_mode: str = "concat"


class ReadFilesStep(BaseStep[ReadFilesConfig]):
    """
    Step that reads one or more files from disk and stores their content in the context.
    Supports templated paths, optional files, and merge modes for multi-file reads.
    """

    def __init__(self, logger: logging.Logger, config: Dict[str, Any]) -> None:
        validated = ReadFilesConfig.model_validate(config)
        super().__init__(logger, validated)

    async def execute(self, context: ContextProtocol) -> None:
        cfg = self.config
        # Render the storage key
        rendered_key = render_template(cfg.content_key, context)

        # Resolve and normalize paths
        raw_path = cfg.path
        paths: List[str] = []

        if isinstance(raw_path, str):
            rendered = render_template(raw_path, context)
            parts = [p.strip() for p in rendered.split(",") if p.strip()]
            paths.extend(parts)
        elif isinstance(raw_path, list):
            for entry in raw_path:
                if not isinstance(entry, str):
                    raise ValueError(f"Invalid path entry type: {entry!r}")
                rendered = render_template(entry, context)
                paths.append(rendered)
        else:
            raise ValueError(f"Invalid type for path: {type(raw_path)}")

        results: List[Any] = []
        result_map: Dict[str, Any] = {}

        for p in paths:
            self.logger.debug(f"Reading file at path: {p}")
            if not os.path.exists(p):
                msg = f"File not found: {p}"
                if cfg.optional:
                    self.logger.warning(f"Optional file missing, skipping: {p}")
                    continue
                raise FileNotFoundError(msg)

            try:
                with open(p, mode="r", encoding="utf-8") as f:
                    text = f.read()
            except Exception as exc:
                raise IOError(f"Error reading file {p}: {exc}")

            # Attempt structured parsing
            ext = os.path.splitext(p)[1].lower()
            content: Any = text
            if ext == ".json":
                try:
                    content = json.loads(text)
                except Exception as exc:
                    self.logger.warning(f"Failed to parse JSON from {p}: {exc}")
            elif ext in (".yaml", ".yml"):
                try:
                    content = yaml.safe_load(text)
                except Exception as exc:
                    self.logger.warning(f"Failed to parse YAML from {p}: {exc}")

            self.logger.info(f"Successfully read file: {p}")
            results.append(content)
            result_map[p] = content

        # Merge results
        if not results:
            if len(paths) <= 1:
                final_content: Any = ""
            elif cfg.merge_mode == "dict":
                final_content = {}
            else:
                final_content = ""
        elif len(results) == 1:
            final_content = results[0]
        else:
            if cfg.merge_mode == "dict":
                final_content = result_map
            else:
                segments: List[str] = []
                for p in paths:
                    if p in result_map:
                        raw = result_map[p]
                        segment = raw if isinstance(raw, str) else json.dumps(raw)
                        segments.append(f"{p}\n{segment}")
                final_content = "\n".join(segments)

        # Store in context
        context[rendered_key] = final_content
        self.logger.info(f"Stored file content under key '{rendered_key}'")
